// Add your new core rgb matrix effect here, order determines enum order
#include "solid_color_anim.h"                       // 1 O
#include "alpha_mods_anim.h"                        // X
#include "gradient_up_down_anim.h"                  // X
#include "gradient_left_right_anim.h"               // 2 O
#include "breathing_anim.h"                         // 3 O
#include "colorband_sat_anim.h"                     // X
#include "colorband_val_anim.h"                     // 4 O
#include "colorband_pinwheel_sat_anim.h"            // X
#include "colorband_pinwheel_val_anim.h"            // 5 O
#include "colorband_spiral_sat_anim.h"              // X
#include "colorband_spiral_val_anim.h"              // 6 O
#include "cycle_all_anim.h"                         // 7 O
#include "cycle_left_right_anim.h"                  // 8 O
#include "cycle_up_down_anim.h"                     // 9 O
#include "rainbow_moving_chevron_anim.h"            // 10 O
#include "cycle_out_in_anim.h"                      // 11 O
#include "cycle_out_in_dual_anim.h"                 // 12 O
#include "cycle_pinwheel_anim.h"                    // 13 O
#include "cycle_spiral_anim.h"                      // 14 O
#include "dual_beacon_anim.h"                       // 15 O
#include "rainbow_beacon_anim.h"                    // 16 O
#include "rainbow_pinwheels_anim.h"                 // 17 O
#include "raindrops_anim.h"                         // X
#include "jellybean_raindrops_anim.h"               // X
#include "hue_breathing_anim.h"                     // X
#include "hue_pendulum_anim.h"                      // X
#include "hue_wave_anim.h"                          // 18 O
#include "pixel_rain_anim.h"                        // 19 O
#include "pixel_flow_anim.h"                        // X
#include "pixel_fractal_anim.h"                     // X
#include "typing_heatmap_anim.h"                    // X
#include "digital_rain_anim.h"                      // X
#include "solid_reactive_simple_anim.h"             // 20 O
#include "solid_reactive_anim.h"                    // 21 O
#include "solid_reactive_wide.h"                    // 22 O (MultiWide)
#include "solid_reactive_cross.h"                   // 23, 24 O (Cross), O (MultiCross)
#include "solid_reactive_nexus.h"                   // 25, 26 O (Nexus), O (MultiNexus)
#include "splash_anim.h"                            // 27, 28 O (Splash), O (MultiSplash)
#include "solid_splash_anim.h"                      // 29, 30 O (SolidSplash), O(SolidMultiSpalsh)
